// scaffords/ice-design-pro/src/pages/EmptyContent/components/EmptyContent/EmptyContent.jsx
import React, { Component } from 'react';
import IceCard from '@icedesign/container';
import './EmptyContent.scss';

export default class EmptyContent extends Component {
  static displayName = 'EmptyContent';

  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <div className="empty-content">
        <IceCard>
          <div style={styles.content}>
            <img
              src="https://img.alicdn.com/tfs/TB1WNNxjBHH8KJjy0FbXXcqlpXa-780-780.png"
              style={styles.image}
              alt="empty"
            />
            <div style={styles.prompt}>
              <h3 style={styles.title}>页面暂无内容</h3>
              <p style={styles.description}>
                抱歉，页面暂无内容，请看看其他页面
              </p>
            </div>
          </div>
        </IceCard>
      </div>
    );
  }
}

const styles = {
  content: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '500px',
  },
  image: { width: '260px', height: '260px', marginRight: '50px' },
  title: { color: '#333', fontSize: '24px', margin: '20px 0' },
  description: { color: '#666' },
};

// vue-materials/blocks/EmptyContent/src/EmptyContent.vue
<template>
  <div className="empty-content">
    <basic-container>
      <div class="exception-content">
        <div class="flex-container align-items-center justify-content-center exception-content">
          <img src="https://img.alicdn.com/tfs/TB1WNNxjBHH8KJjy0FbXXcqlpXa-780-780.png" class="imgException"/>
          <div>
            <h3 class="title">页面暂无内容</h3>
            <p class="description">抱歉，页面暂无内容，请看看
              <router-link to="/">其他页面</router-link>继续浏览
            </p>
          </div>
        </div>
      </div>
    </basic-container>
  </div>
</template>

<script>
import BasicContainer from '@vue-materials/basic-container'

export default {
  components: { BasicContainer },
  name: 'EmptyContent',
  data() {
    return {}
  }
}

</script>

<style lang="scss" scoped>
/**flex相关 */
.flex-container{
  display: flex;
}
.align-items-center{
  align-items: center;
}
.justify-content-center{
  justify-content: center
}

.exception-content {
  .title {
    color: rgb(51, 51, 51);
  }
  .description {
    color: rgb(102, 102, 102);
  }
}
@media screen and (max-width: 1199px) and (min-width: 721px) {
  .exception-content {
    .imgException {
      max-width: 180px;
      margin-right: 30px;
    }
    .title {
      font-size: 20px;
      margin: 10px 0;
    }
    .description {
      font-size: 14px;
    }
  }
}
@media screen and (min-width: 1200px) {
  .exception-content {
    .imgException {
      max-width: 260px;
      margin-right: 50px;
    }
    .title {
      font-size: 24px;
      margin: 20px 0;
    }
    .description {
      font-size: 16px;
    }
  }
}
</style>
