// react-materials/blocks/SimpleFooter/src/SimpleFooter.jsx
import React, { Component } from 'react';
import IceContainer from '@icedesign/container';
import { Grid } from '@icedesign/base';

const { Row, Col } = Grid;

export default class SimpleFooter extends Component {
  static displayName = 'SimpleFooter';

  static propTypes = {};

  static defaultProps = {};

  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <div className="simple-footer">
        <IceContainer>
          <Row wrap style={styles.content}>
            <Col l="4" xxs="24">
              <a href="#" style={styles.brand}>
                <img
                  src="https://img.alicdn.com/tfs/TB1saOBbYGYBuNjy0FoXXciBFXa-218-58.png"
                  alt=""
                  style={styles.logo}
                />
              </a>
            </Col>
            <Col l="20" xxs="24">
              <div style={styles.nav}>
                <a href="#" style={styles.navLink}>
                  Home
                </a>
                <a href="#" style={styles.navLink}>
                  Shop
                </a>
                <a href="#" style={styles.navLink}>
                  Blog
                </a>
                <a href="#" style={styles.navLink}>
                  Service
                </a>
                <a href="#" style={styles.navLink}>
                  About
                </a>
                <a href="#" style={{ ...styles.navLink, marginRight: 0 }}>
                  Contact
                </a>
              </div>
            </Col>
          </Row>
        </IceContainer>
      </div>
    );
  }
}

const styles = {
  content: {
    alignItems: 'center',
  },
  logo: {
    width: '86px',
  },
  nav: {
    textAlign: 'right',
  },
  navLink: {
    marginRight: '20px',
    color: 'rgba(0, 0, 0, 0.87)',
  },
};

// vue-materials/blocks/SimpleFooter/src/SimpleFooter.vue
<template>
  <div class="simple-footer">
    <basic-container>
      <div class="footer-row">
        <a class="footer-brand" href="">
          <img class="footer-logo" :src="logo" alt="logo">
        </a>
        <ul class="footer-list">
          <li class="footer-list-item" v-for="(item,index) in navList" :key="index">
            <a :href="item.link">{{ item.title }}</a>
          </li>
        </ul>
      </div>
    </basic-container>
  </div>
</template>

<script>
import BasicContainer from '@vue-materials/basic-container';

export default {
  components: { BasicContainer },
  name: 'SimpleFooter',

  data() {
    return {
      logo: 'https://img.alicdn.com/tfs/TB1saOBbYGYBuNjy0FoXXciBFXa-218-58.png',
      navList: [
        { title: 'Home', link: '#' },
        { title: 'Shop', link: '#' },
        { title: 'Blog', link: '#' },
        { title: 'Service', link: '#' },
        { title: 'About', link: '#' },
        { title: 'Contact', link: '#' },
      ],
    };
  },

  created() {},

  methods: {},
};
</script>

<style lang="scss" scoped>
@import '~normalize.css/normalize.css';

.simple-footer {
  .footer-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    .footer-logo {
      width: 86px;
    }
    .footer-list {
      display: flex;
      justify-content: flex-start;
      text-align: right;
      font-size: 14px;
      &-item {
        list-style: none;
        margin-right: 20px;
        color: rgba(0, 0, 0, 0.87);
        &:last-child {
          margin-right: 0;
        }
        & > a {
          text-decoration: none;
          color: #333;
        }
      }
    }
  }
}
</style>
