// react-materials/blocks/BasicException/src/BasicException.jsx
import React, { Component } from 'react';
import IceContainer from '@icedesign/container';
import './BasicException.scss';

export default class BasicException extends Component {
  static displayName = 'BasicException';
  render() {
    return (
      <div className="basic-exception">
        <IceContainer>
          <div style={styles.exceptionContent} className="exception-content">
            <img
              src="https://img.alicdn.com/tfs/TB1w4M7bNrI8KJjy0FpXXb5hVXa-260-260.png"
              style={styles.imgException}
              className="imgException"
              alt="服务器出错"
            />
            <div>
              <h3 style={styles.title} className="title">
                抱歉，服务器出错了
              </h3>
              <p style={styles.description} className="description">
                服务器出错了，请重新刷新页面或返回<a href="#">首页</a>
              </p>
            </div>
          </div>
        </IceContainer>
      </div>
    );
  }
}

const styles = {
  exceptionContent: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#333',
  },
  description: {
    color: '#666',
  },
};

// vue-materials/blocks/BasicException/src/BasicException.vue
<template>
  <div className="basic-exception">
    <basic-container>
      <div class="exception-content">
        <div class="flex-container align-items-center justify-content-center exception-content">
          <img src="https://img.alicdn.com/tfs/TB1w4M7bNrI8KJjy0FpXXb5hVXa-260-260.png" class="imgException"/>
          <div>
            <h3 class="title">抱歉，服务器出错了</h3>
            <p class="description" >服务器出错了，请重新刷新页面或返回
              <router-link to="/">首页</router-link>
            </p>
          </div>
        </div>
      </div>
    </basic-container>
  </div>
</template>

<script>
import BasicContainer from '@vue-materials/basic-container';

export default {
  components: { BasicContainer },
  name: 'BasicException',
  data() {
    return {};
  }
};
</script>

<style lang="scss" scoped>
/**flex相关 */
.flex-container{
  display: flex;
}
.align-items-center{
  align-items: center;
}
.justify-content-center{
  justify-content: center
}

.exception-content {
  .title {
    color: rgb(51, 51, 51);
  }
  .description {
    color: rgb(102, 102, 102);
  }
}

@media screen and (max-width: 1199px) and (min-width: 721px) {
  .exception-content {
    .imgException {
      max-width: 180px;
      margin-right: 30px;
    }
    .title {
      font-size: 20px;
      margin: 10px 0;
    }
    .description {
      font-size: 14px;
    }
  }
}
@media screen and (min-width: 1200px) {
  .exception-content {
    .imgException {
      max-width: 260px;
      margin-right: 50px;
    }
    .title {
      font-size: 24px;
      margin: 20px 0;
    }
    .description {
      font-size: 16px;
    }
  }
}
</style>
