// vue-materials/blocks/DataDisplay/src/DataDisplay.vue
<template>
  <div class="data-display">
    <basic-container>
      <el-row :span="24">
        <el-col v-for="(item,index) in option.data" :key="index" :span="option.span">
          <div class="item" :style="{color:option.color}">
            <h5 class="count">{{item.count}}</h5>
            <span class="splitLine" />
            <p class="title">{{item.title}}</p>
          </div>
        </el-col>
      </el-row>

    </basic-container>
  </div>
</template>

<script>
import BasicContainer from '@vue-materials/basic-container';
export default {
  components: { BasicContainer },
  name: 'DataDisplay',
  data() {
    return {
      option: {
        span: 8,
        color: '#15A0FF',
        data: [
          {
            count: 100,
            title: '日活跃数',
          },
          {
            count: '3,000',
            title: '月活跃数',
          },
          {
            count: '20,000',
            title: '年活跃数',
          },
        ],
      },
    };
  },

  created() {},
};
</script>
<style lang="scss" scoped>
@import './DataDisplay.scss';
</style>

// scaffords/ice-design-pro/src/pages/CardList/components/DataDisplay/DataDisplay.jsx
import React, { Component } from 'react';
import IceCard from '@icedesign/container';
import './DataDisplay.scss';

const data = [
  {
    count: 100,
    title: '日活跃数',
  },
  {
    count: '3,000',
    title: '月活跃数',
  },
  {
    count: '20,000',
    title: '年活跃数',
  },
];

export default class DataDisplay extends Component {
  static displayName = 'DataDisplay';

  static propTypes = {};

  static defaultProps = {};

  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <div className="data-display">
        <IceCard>
          <div style={styles.items}>
            {data.map((item, index) => {
              return (
                <div style={styles.item} key={index}>
                  <h5 style={styles.count}>{item.count}</h5>
                  <span style={styles.splitLine} />
                  <p style={styles.title}>{item.title}</p>
                </div>
              );
            })}
          </div>
        </IceCard>
      </div>
    );
  }
}

const styles = {
  items: {
    display: 'flex',
    flexWrap: 'wrap',
  },
  item: {
    width: '33%',
    margin: '20px 0',
    textAlign: 'center',
  },
  count: {
    margin: '12px 0',
    fontWeight: 'bold',
    fontSize: '32px',
    color: '#15A0FF',
  },
  title: {
    color: '#999',
  },
  splitLine: {
    display: 'block',
    margin: '0 auto',
    width: '24px',
    height: '1px',
    background: '#9B9B9B',
  },
};
